language: android
android:
  components:
    - android-19
    - android-20
    - build-tools-20.0.0
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+
before_install:
  - openssl aes-256-cbc -K $encrypted_5ebf751f8018_key -iv $encrypted_5ebf751f8018_iv -in key.p12.enc -out key.p12 -d
  - export PATH=${PATH}:${ANDROID_HOME}/build-tools/20.0.0
  - gem install git
  - gem install htmlentities
  - git fetch origin master
  - git fetch --all
before_script:
- openssl aes-256-cbc -k "$KEYSTORE_FILE_PASSWORD" -in release.keystore.enc -d -a
  -out release.keystore
script:
- scripts/processChangelog ./ > app/src/main/res/xml/changelog_master.xml
- cat app/src/main/res/xml/changelog_master.xml
- "./gradlew build assembleRelease"
- if [ "$TRAVIS_BRANCH" = "develop" ]; then ./testfairy-upload.sh app/build/outputs/apk/app-release.apk; fi;
- if [ "$TRAVIS_BRANCH" = "develop" ]; then python scripts/uploadApk.py de.happycarl.geotown.app alpha app/build/outputs/apk/app-release.apk; fi;
- if [ -z "$TRAVIS_TAG" ]; then python scripts/uploadApk.py de.happycarl.geotown.app production app/build/outputs/apk/app-release.apk; fi;
env:
  global:
  - secure: WR7j7bQVR5IAvn4fR9xT5IyQglUxmmDj3ohzrSVmTwDCuHEo/QuZX5QxpJHIciSNUBDEiAIQYmtvYredIdoPk3W0s8d7PCYhMdiKgojs/dD65BfxiXDlEos7Y/seTO84m4M10MN0nnwTf8owzlO9FMQioLbDFzJUTQU9d3/wdCo=
  - secure: Tk776qT+UkyaWF2h3jSSoCLYBKFTekTJLnPwMg+XBj41ChjeUppvjwlYV5uRpRi9s+4CGW/FT1odafofGrJ7TfgKj49C/6DbaNHSCgEdLKvAdn2BjirlaYzJtf7vBy+VD1u7/13m849EO4o16xrWgHzRBJXJ9pZmYeHt5nUGk3I=
  - secure: g/LSBmGJMqtgbe+GXZMlAbyMQSkpy7sih7e+3JgfyoyCO84fyos4otZlLgmEwleiYYxBOBAgEBnQfANnbL6cN9YXVowRVSw8bzOr/nqjWfJ7OtWQUOwz6KtKIeOvWAALzivGxU7LCagGuvmpUNKmbrHKzUQFGUxpokGvy66uYh4=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FGUpXcIJLqZTKg57W/UqiGuEEykA6yJuUaifxNr0LzA0WhqMvLYJV20p9QtGiS30/qKPC8MqoUjGlwzQpmtwOz5XYcLhxYXTAG42/ZTIwfn1B4mERfGZ0KthWXVfvz+sXUEAM9tM8uWaySOmalZTAQ4cfmGvf1qJubABcDm3VDg=
  file: "app/build/outputs/apk/app-release.apk"
  on:
    tags: true
    all_branches: true
    repo: HappyCarl/geotown.android
