language: android
android:
  licenses:
    - android-sdk-license-5be876d5 # new license!
    - android-sdk-license-598b93a6
before_install:
  - #sudo apt-get update -qq
  - #if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - #wget http://dl.google.com/android/android-sdk_r23-linux.tgz
  - #tar xzf android-sdk_r23-linux.tgz
  - #export ANDROID_HOME=$PWD/android-sdk-linux
  - #export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  - #( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk -a --filter platform-tools,tools --no-ui --force
  - #( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk -a --filter build-tools-20.0.0,android-19,extra-google-m2repository,extra-android-m2repository,extra-android-support,extra-google-google_play_services --no-ui --force
  - 'sudo mv /usr/local/android-sdk/tools/android-* /usr/local/bin'
  - "android-update-sdk --components='platform-tools,tools' --accept-licenses='.+'"
  - "android-update-sdk --components='build-tools-20.0.0' --accept-licenses='.+'"
  - "android-update-sdk --components='android-20,android-19' --accept-licenses='.+'"
  - "android-update-sdk --components='extra-android-m2repository,extra-google-m2repository' --accept-licenses='.+'"
  - export PATH=${PATH}:${ANDROID_HOME}/build-tools/20.0.0
  - gem install katip
  - gem install redcarpet
before_script:
- openssl aes-256-cbc -k "$KEYSTORE_FILE_PASSWORD" -in release.keystore.enc -d -a
  -out release.keystore
script:
- katip
- scripts/processChangelog CHANGELOG.md > app/src/main/res/xml/changelog_master.xml
- "./gradlew build assembleRelease"
- if [ "$TRAVIS_BRANCH" = "develop" ]; then ./testfairy-upload.sh app/build/outputs/apk/app-release.apk; fi;
env:
  global:
  - secure: WR7j7bQVR5IAvn4fR9xT5IyQglUxmmDj3ohzrSVmTwDCuHEo/QuZX5QxpJHIciSNUBDEiAIQYmtvYredIdoPk3W0s8d7PCYhMdiKgojs/dD65BfxiXDlEos7Y/seTO84m4M10MN0nnwTf8owzlO9FMQioLbDFzJUTQU9d3/wdCo=
  - secure: Tk776qT+UkyaWF2h3jSSoCLYBKFTekTJLnPwMg+XBj41ChjeUppvjwlYV5uRpRi9s+4CGW/FT1odafofGrJ7TfgKj49C/6DbaNHSCgEdLKvAdn2BjirlaYzJtf7vBy+VD1u7/13m849EO4o16xrWgHzRBJXJ9pZmYeHt5nUGk3I=
  - secure: g/LSBmGJMqtgbe+GXZMlAbyMQSkpy7sih7e+3JgfyoyCO84fyos4otZlLgmEwleiYYxBOBAgEBnQfANnbL6cN9YXVowRVSw8bzOr/nqjWfJ7OtWQUOwz6KtKIeOvWAALzivGxU7LCagGuvmpUNKmbrHKzUQFGUxpokGvy66uYh4=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FGUpXcIJLqZTKg57W/UqiGuEEykA6yJuUaifxNr0LzA0WhqMvLYJV20p9QtGiS30/qKPC8MqoUjGlwzQpmtwOz5XYcLhxYXTAG42/ZTIwfn1B4mERfGZ0KthWXVfvz+sXUEAM9tM8uWaySOmalZTAQ4cfmGvf1qJubABcDm3VDg=
  file: "app/build/outputs/apk/app-release.apk"
  on:
    tags: true
    all_branches: false
    repo: HappyCarl/geotown.android
