#!/usr/bin/env ruby
require 'open-uri'
require 'json'
require 'git'

g = Git.open(ARGV[0])

  builds = JSON.parse(open("https://api.travis-ci.org/repos/HappyCarl/geotown.android/builds").read)

currentVersion = "Beta"
beta = true
lastVersion = ""
lastCommit = builds[0]['commit']
first = true

puts "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<changelog>"

builds.each do |b|

  begin
    currentVersion = g.tag(b['branch']).name
    beta = false
  rescue Git::GitTagNameDoesNotExist
  end
  if beta
    currentVersion = "Beta ##{b['number']}"
  end

  puts "\t</release>" if currentVersion != lastVersion and not first
  puts "\t<release version=\"#{currentVersion}\" versioncode=\"#{b['number']}\">" if currentVersion != lastVersion

  commit = b['commit']

  begin
    puts "\t\t<change>#{g.object(commit).message}</change>"
  rescue Git::GitExecuteError
    puts "\t\t<change>Coded Stuff.</change>"
  end

  lastVersion = currentVersion
  lastCommit = commit
  first = false

end

puts "\t</release>"
puts "</changelog>"
