#!/usr/bin/env ruby
require 'open-uri'
require 'json'
require 'git'

g = Git.open(ARGV[0])

builds = JSON.parse(open("https://api.travis-ci.org/repos/HappyCarl/geotown.android/builds").read)

currentVersion = "Beta"
beta = true
lastVersion = ""
lastCommit = builds[0]['commit']

builds.each do |b|
  begin
    currentVersion = g.tag(b['branch']).name
    beta = false
  rescue Git::GitTagNameDoesNotExist
  end
  if beta
    currentVersion = "Beta ##{b['number']}"
  end
  puts currentVersion if currentVersion != lastVersion
  commit = b['commit']
  
  if commit == lastCommit
    puts g.object(commit).message
  else
    g.log.between(commit, lastCommit).each do |c|
      puts c.message
    end
  end
  
  
  lastVersion = currentVersion
  lastCommit = commit
end
